name: 'Setup'
description: 'Setup project for CI'

inputs:
  db_host:
    description: 'Database host'
    required: true

  db_port:
    description: 'Database port'
    required: true

  db_username:
    description: 'Database username'
    required: true

  db_password:
    description: 'Database password'
    required: true

outputs:
  yarn-cache:
    description: 'Yarn cache folder'
    value: ${{ steps.cache.outputs.yarn-cache }}

runs:
  using: composite

  steps:
    # Configure yarn cache
    - run: echo "::set-output name=yarn-cache::$(yarn cache dir)"
      id: cache
      shell: bash

    # Configure typeorm
    - run: |
        sed -i "s/\"host\": \".*\"/\"host\": \"$INPUT_DB_HOST\"/g" ormconfig.json
        sed -i "s/\"port\": [0-9]*/\"port\": $INPUT_DB_PORT/g" ormconfig.json
        sed -i "s/\"username\": \".*\"/\"username\": \"$INPUT_DB_USERNAME\"/g" ormconfig.json
        sed -i "s/\"password\": \".*\"/\"password\": \"$INPUT_DB_PASSWORD\"/g" ormconfig.json
        cat ormconfig.json
      shell: bash
