version: '3'

networks:
  lucifer:

services:
  postgres:
    image: postgres:12-alpine
    restart: unless-stopped
    volumes:
      - ./db/data:/var/lib/postgresql/data
    networks:
      lucifer:
        aliases:
          - postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root

  lucifer-api:
    image: ghcr.io/jujulego/lucifer/lucifer-api:master
    restart: unless-stopped
    networks:
      lucifer:
        aliases:
          - lucifer-api
    ports:
      - 3333:80
    environment:
      DATABASE_URL: postgres://root:root@postgres:5432
