name: 'Setup Database'
description: 'Setup typeorm for CI'

inputs:
  db-host:
    description: 'Database host'
    required: true

  db-port:
    description: 'Database port'
    required: true

  db-username:
    description: 'Database username'
    required: true

  db-password:
    description: 'Database password'
    required: true

runs:
  using: node12
  main: index.js
