name: Docs

on:
  push:
    branches: [ master ]

jobs:
  deploy-docs:
    runs-on: ubuntu-latest
    environment: github-pages

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Setup Cache
        id: setup-cache
        run: echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - uses: actions/cache@v2.1.5
        with:
          path: |
            ${{ steps.setup-cache.outputs.yarn-cache }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Build storybook
        run: yarn nx run storybook:build-storybook

      - name: Deploy docs
        uses: JamesIves/github-pages-deploy-action@4.1.3
        with:
          branch: docs # The branch the action should deploy to.
          folder: dist/storybook/storybook # The folder the action should deploy.
          clean: true # Automatically remove deleted files from the deploy branch
