name: Prod

on:
  push:
    branches: [master]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Setup Cache
        id: setup-cache
        run: echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.setup-cache.outputs.yarn-cache }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn run nx run-many --all --target=lint --scan

  tests:
    runs-on: ubuntu-latest
    needs: lint

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: 'root'
          POSTGRES_PASSWORD: 'root'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      AUTH0_DOMAIN: 'test.com'
      AUTH0_AUDIENCE: 'test'
      AUTH0_CLIENT_ID: 'test'
      AUTH0_CLIENT_SECRET: 'test'

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Setup Cache
        id: setup-cache
        run: echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - name: Setup Database
        uses: ./.github/actions/setup-db
        with:
          db-host: 'localhost'
          db-port: 5432
          db-username: 'root'
          db-password: 'root'

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.setup-cache.outputs.yarn-cache }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn run build:tools

      - name: Migrate
        run: yarn run nx run-many --all --target=db-migrate --scan

      - name: Tests
        run: yarn run nx run-many --all --target=test --scan --codeCoverage --coverageReporters=clover,lcovonly,json

      - name: Codecov
        uses: codecov/codecov-action@v1.3.1
        with:
          flags: unit

  build:
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Setup Cache
        id: setup-cache
        run: echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.setup-cache.outputs.yarn-cache }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn run build:tools

      - name: Build
        run: yarn run nx run-many --all --target=build --scan --prod

      - name: Archive build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: build
          path: dist

      - name: Archive rules artifacts
        uses: actions/upload-artifact@v2
        with:
          name: rules
          path: res/rules

  terraform:
    runs-on: ubuntu-latest
    needs: [build, tests]

    steps:
      - uses: actions/checkout@v2

      - name: Download rules artifacts
        uses: actions/download-artifact@v2
        with:
          name: rules
          path: res/rules

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

      - name: Terraform Format
        run: terraform fmt -check
        working-directory: ./res

      - name: Terraform Init
        run: terraform init
        working-directory: ./res

      - name: Terraform Apply
        run: terraform apply -auto-approve
        working-directory: ./res

  docker:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/checkout@v2

      - name: Download build artifacts
        uses: actions/download-artifact@v2
        with:
          name: build
          path: dist

      - name: Prepare
        id: prep
        run: |
          DOCKER_IMAGE=ghcr.io/${{ github.repository }}/lucifer-api
          VERSION=edge
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
          elif [[ $GITHUB_REF == refs/heads/* ]]; then
            VERSION=$(echo ${GITHUB_REF#refs/heads/} | sed -r 's#/+#-#g')
          elif [[ $GITHUB_REF == refs/pull/* ]]; then
            VERSION=pr-${{ github.event.number }}
          fi
          TAGS="${DOCKER_IMAGE,,}:${VERSION}"
          if [ "${{ github.event_name }}" = "push" ]; then
            TAGS="$TAGS,${DOCKER_IMAGE,,}:sha-${GITHUB_SHA::8}"
          fi
          echo ::set-output name=version::${VERSION}
          echo ::set-output name=tags::${TAGS}
          echo ::set-output name=created::$(date -u +'%Y-%m-%dT%H:%M:%SZ')

      - name: Setup QEMU
        uses: docker/setup-qemu-action@v1

      - name: Setup Docker
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          push: true
          file: apps/lucifer-api/Dockerfile
          context: .
          build-args: |
            "Auth0Domain=jujulego.eu.auth0.com"
            "Auth0Audience=https://lucifer-api.herokuapp.com/"
            "Auth0ClientId=Ni7eCeRfTINTJeDBlXyxtavguBCQR6iH"
            "Auth0ClientSecret=${{ secrets.AUTH0_CLIENT_SECRET }}"
          labels: |
            org.opencontainers.image.source=${{ github.event.repository.html_url }}
            org.opencontainers.image.created=${{ steps.prep.outputs.created }}
            org.opencontainers.image.revision=${{ github.sha }}
          tags:  ${{ steps.prep.outputs.tags }}

  e2e-tests:
    runs-on: ubuntu-latest
    needs: terraform

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: 'root'
          POSTGRES_PASSWORD: 'root'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 14.x
        uses: actions/setup-node@v2.1.5
        with:
          node-version: 14.x

      - name: Setup Cache
        id: setup-cache
        run: echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - name: Setup Database
        uses: ./.github/actions/setup-db
        with:
          db-host: 'localhost'
          db-port: 5432
          db-username: 'root'
          db-password: 'root'

      - uses: actions/cache@v2.1.4
        with:
          path: |
            ${{ steps.setup-cache.outputs.yarn-cache }}
            ~/.cache/Cypress
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --frozen-lockfile
          yarn run build:tools

      - name: Migrate
        run: yarn run nx run-many --all --target=db-migrate --scan

      - name: Start & Seed API
        run: |
          yarn run nx run lucifer-api:serve:e2e &
          yarn run nx run lucifer-api:seed --scan
          yarn run nx run lucifer-api:wait
        env:
          PORT: 3333

          AUTH0_DOMAIN: jujulego.eu.auth0.com
          AUTH0_AUDIENCE: 'https://lucifer-api.herokuapp.com/'
          AUTH0_CLIENT_ID: Ni7eCeRfTINTJeDBlXyxtavguBCQR6iH
          AUTH0_CLIENT_SECRET: ${{ secrets.AUTH0_CLIENT_SECRET }}

      - name: E2E Tests
        run: |
          echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
          yarn run nx run-many --all --target=e2e --scan --skip-nx-cache
        env:
          CYPRESS_Auth0ClientSecret: ${{ secrets.E2E_AUTH0_CLIENT_SECRET }}

      - name: Codecov
        uses: codecov/codecov-action@v1.3.1
        with:
          flags: e2e

      - name: Archive cypress results
        uses: actions/upload-artifact@v2
        with:
          name: cypress-results
          path: dist/cypress
