name: Push

on:
  push:
    branches: [ master ]

env:
  NX_BRANCH: ${{ github.event.number }}
  NX_RUN_GROUP: ${{ github.run_id }}

jobs:
  tests:
    runs-on: ubuntu-latest

    container:
      image: node:14

    services:
      postgres:
        image: postgres:12-alpine
        env:
          POSTGRES_USER: 'root'
          POSTGRES_PASSWORD: 'root'
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    env:
      AUTH0_DOMAIN: 'test.com'
      AUTH0_AUDIENCE: 'test'
      AUTH0_CLIENT_ID: 'test'
      AUTH0_CLIENT_SECRET: 'test'

    steps:
      - uses: actions/checkout@v2

      - name: 'Setup'
        id: setup
        uses: ./.github/actions/setup
        with:
          db-host: 'postgres'
          db-port: 5432
          db-username: 'root'
          db-password: 'root'

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup.outputs.yarn-cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: |
          yarn install --pure-lockfile
          yarn run build:tools

      - name: Lint
        run: yarn run nx run-many --all --target=lint --scan

      - name: Migrate
        run: yarn run nx run-many --all --target=db-migrate --scan

      - name: Tests
        run: yarn run nx run-many --all --target=test --scan

  build:
    runs-on: ubuntu-latest
    needs: tests

    container:
      image: node:14

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        id: setup
        run: |
          # Configure yarn cache
          echo "::set-output name=yarn-cache::$(yarn cache dir)"

      - uses: actions/cache@v2
        with:
          path: ${{ steps.setup.outputs.yarn-cache }}
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: ${{ runner.os }}-yarn-

      - name: Install dependencies
        run: yarn install --pure-lockfile

      - name: Build
        run: yarn run nx run-many --all --target=build --scan

      - name: Archive production artifacts
        uses: actions/upload-artifact@v2
        with:
          name: production-build
          path: dist
